# Server
source: docs
destination: _gh_pages

# Custom vars
repo: https://github.com/vsn4ik/bootstrap-checkbox
description: A checkbox component based on Bootstrap framework.

download:
  dist: https://github.com/vsn4ik/bootstrap-checkbox/releases/download/v1.2.7/bootstrap-checkbox-1.2.7-dist.zip
